### ISSUE TITLE
[feature request] Allow an alternative name for the custom endpoint

### ISSUE THREAD

**Issue by egarbi** [idealo/terraform-aws-opensearch#25]
The module will create a new cluster named "cluster_name" and create a custom endpoint based on that name. That's fine but allowing us to pass an alternative name will allow us to import an existing module into terraform.

If you are fine with this feature I can push a PR

**Comment by steveteuber** [comment]
Hi @egarbi, pull requests are always welcome!

**Comment by svanschalkwyk** [comment]
Is it possible to have the option to just have a private endpoint for those who are not allowed to use public Hosted Endpoints?

**Comment by steveteuber** [comment]
Hi @svanschalkwyk,

Sure of course you can use a private DNS zone when you don't want/can use a public endpoint: https://github.com/idealo/terraform-aws-opensearch#input_cluster_domain_private

**Comment by svanschalkwyk** [comment]
Much appreciated!

**Comment by egarbi** [comment]
@steveteuber can you review the PR, please?
