### ISSUE TITLE
[Bug] Unrecognized advanced option "override_main_response_version"

### ISSUE THREAD

**Issue by theurichde** [idealo/terraform-aws-opensearch#29]
Hi there 👋🏼 

When bumping the module version from 1.2.0 to 1.3.0 I get an `ValidationException` when running terraform apply, stating that the newly introduced advanced option `override_main_response_version` is unrecognized.

We are running OpenSearch 1.3 on AWS

    module.opensearch.aws_elasticsearch_domain.opensearch: Modifying... [id=arn:aws:es:eu-central-1:***:domain/logging]
    ╷
    │ Error: updating Elasticsearch Domain (arn:aws:es:eu-central-1:***:domain/logging) config: ValidationException: Unrecognized advanced option 'override_main_response_version' passed in advancedOptions.
    │ 
    │   with module.opensearch.aws_elasticsearch_domain.opensearch,
    │   on .terraform/modules/opensearch/main.tf line 24, in resource "aws_elasticsearch_domain" "opensearch":
    │   24: resource "aws_elasticsearch_domain" "opensearch" {
    │

**Comment by steveteuber** [comment]
Hi @theurichde,

Thank you for opening this issue. It seems that this option can only be enabled via the OpenSearch dev tools...
I think I'll fix that issue by removing the new defaults for `advanced_options`.
