### ISSUE TITLE
[BUG]  Error: timeout after 5 seconds while pinging '...' to determine server version

### ISSUE THREAD

**Issue by damianwnukowski** [idealo/terraform-aws-opensearch#33]
Hi. I have a problem with `terraform apply`, I'm getting  
│ Error: timeout after 5 seconds while pinging '(public url to domain was here)'  to determine server version, please consider setting 'elasticsearch_version' to avoid this lookup
With vpc_enabled = true. Am I doing something wrong or is this a bug? I guess it shouldn't try to reach out to this domain because it's inside VPC as intended.

**Comment by steveteuber** [comment]
Hey @damianwnukowski,

Thank you for opening this issue. When you create your OpenSearch cluster in a VPC, you need to run Terraform in the VPC as well. Otherwise the cluster is not reachable for Terraform to create indices, index templates, roles, etc.
