### ISSUE TITLE
[BUG] How to specify additional parameters for opensearchserverless_collectio\n

### ISSUE THREAD

**Issue by balaji-punniyakodi** [idealo/terraform-aws-opensearch#40]
Hi Team, 

I can see you have recently created aws_opensearchserverless_collection resource https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/opensearchserverless_collection.html.markdown however I dont see the parameter to specify the KMS key, network settings (Public or private with VPCE endpoints) from terraform and resource type. 
![resource types](https://github.com/idealo/terraform-aws-opensearch/assets/136547507/025090ff-8565-48c8-b7c5-c88ae0ebd42b)
![kmskey](https://github.com/idealo/terraform-aws-opensearch/assets/136547507/7160dbb7-ee40-4056-bfc5-e7c8604ab7d9)

![networksettings](https://github.com/idealo/terraform-aws-opensearch/assets/136547507/62887983-1963-4cea-a272-2a9769d40a13)

Let us know if you have any further queries.

**Comment by steveteuber** [comment]
Hi @balaji-punniyakodi,

This module currently doesn't support AWS OpenSearch Serverless.
But you can create a pull request for that feature 😄
