### ISSUE TITLE
`custom_endpoint_enabled` enforced

### ISSUE THREAD

**Issue by pielu** [idealo/terraform-aws-opensearch#42]
Hello,

Is there any reason for `custom_endpoint_enabled` being enforced to `true`?

**Comment by steveteuber** [comment]
Hey @pielu,

Yes because provider configuration must be known and valid at plan time, see https://github.com/hashicorp/terraform/issues/2430.
Otherwise it isn't possible create OpenSearch resources right after creating the cluster.
